// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ComplexBlob.proto

package test;

public final class ComplexBlob {
  private ComplexBlob() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SelfBlobOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .test.SubGroup blob = 1;
    /**
     * <code>optional .test.SubGroup blob = 1;</code>
     */
    boolean hasBlob();
    /**
     * <code>optional .test.SubGroup blob = 1;</code>
     */
    test.ComplexBlob.SubGroup getBlob();
    /**
     * <code>optional .test.SubGroup blob = 1;</code>
     */
    test.ComplexBlob.SubGroupOrBuilder getBlobOrBuilder();

    // required int32 testInt = 2;
    /**
     * <code>required int32 testInt = 2;</code>
     */
    boolean hasTestInt();
    /**
     * <code>required int32 testInt = 2;</code>
     */
    int getTestInt();
  }
  /**
   * Protobuf type {@code test.SelfBlob}
   */
  public static final class SelfBlob extends
      com.google.protobuf.GeneratedMessage
      implements SelfBlobOrBuilder {
    // Use SelfBlob.newBuilder() to construct.
    private SelfBlob(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SelfBlob(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SelfBlob defaultInstance;
    public static SelfBlob getDefaultInstance() {
      return defaultInstance;
    }

    public SelfBlob getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SelfBlob(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              test.ComplexBlob.SubGroup.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = blob_.toBuilder();
              }
              blob_ = input.readMessage(test.ComplexBlob.SubGroup.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(blob_);
                blob_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              testInt_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.ComplexBlob.internal_static_test_SelfBlob_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.ComplexBlob.internal_static_test_SelfBlob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.ComplexBlob.SelfBlob.class, test.ComplexBlob.SelfBlob.Builder.class);
    }

    public static com.google.protobuf.Parser<SelfBlob> PARSER =
        new com.google.protobuf.AbstractParser<SelfBlob>() {
      public SelfBlob parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SelfBlob(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SelfBlob> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .test.SubGroup blob = 1;
    public static final int BLOB_FIELD_NUMBER = 1;
    private test.ComplexBlob.SubGroup blob_;
    /**
     * <code>optional .test.SubGroup blob = 1;</code>
     */
    public boolean hasBlob() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .test.SubGroup blob = 1;</code>
     */
    public test.ComplexBlob.SubGroup getBlob() {
      return blob_;
    }
    /**
     * <code>optional .test.SubGroup blob = 1;</code>
     */
    public test.ComplexBlob.SubGroupOrBuilder getBlobOrBuilder() {
      return blob_;
    }

    // required int32 testInt = 2;
    public static final int TESTINT_FIELD_NUMBER = 2;
    private int testInt_;
    /**
     * <code>required int32 testInt = 2;</code>
     */
    public boolean hasTestInt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 testInt = 2;</code>
     */
    public int getTestInt() {
      return testInt_;
    }

    private void initFields() {
      blob_ = test.ComplexBlob.SubGroup.getDefaultInstance();
      testInt_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTestInt()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasBlob()) {
        if (!getBlob().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, blob_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, testInt_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, blob_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, testInt_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static test.ComplexBlob.SelfBlob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.ComplexBlob.SelfBlob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.ComplexBlob.SelfBlob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.ComplexBlob.SelfBlob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.ComplexBlob.SelfBlob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.ComplexBlob.SelfBlob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static test.ComplexBlob.SelfBlob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static test.ComplexBlob.SelfBlob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static test.ComplexBlob.SelfBlob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.ComplexBlob.SelfBlob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(test.ComplexBlob.SelfBlob prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.SelfBlob}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements test.ComplexBlob.SelfBlobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.ComplexBlob.internal_static_test_SelfBlob_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.ComplexBlob.internal_static_test_SelfBlob_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.ComplexBlob.SelfBlob.class, test.ComplexBlob.SelfBlob.Builder.class);
      }

      // Construct using test.ComplexBlob.SelfBlob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBlobFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (blobBuilder_ == null) {
          blob_ = test.ComplexBlob.SubGroup.getDefaultInstance();
        } else {
          blobBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        testInt_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.ComplexBlob.internal_static_test_SelfBlob_descriptor;
      }

      public test.ComplexBlob.SelfBlob getDefaultInstanceForType() {
        return test.ComplexBlob.SelfBlob.getDefaultInstance();
      }

      public test.ComplexBlob.SelfBlob build() {
        test.ComplexBlob.SelfBlob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public test.ComplexBlob.SelfBlob buildPartial() {
        test.ComplexBlob.SelfBlob result = new test.ComplexBlob.SelfBlob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (blobBuilder_ == null) {
          result.blob_ = blob_;
        } else {
          result.blob_ = blobBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.testInt_ = testInt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.ComplexBlob.SelfBlob) {
          return mergeFrom((test.ComplexBlob.SelfBlob)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.ComplexBlob.SelfBlob other) {
        if (other == test.ComplexBlob.SelfBlob.getDefaultInstance()) return this;
        if (other.hasBlob()) {
          mergeBlob(other.getBlob());
        }
        if (other.hasTestInt()) {
          setTestInt(other.getTestInt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestInt()) {
          
          return false;
        }
        if (hasBlob()) {
          if (!getBlob().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.ComplexBlob.SelfBlob parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.ComplexBlob.SelfBlob) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .test.SubGroup blob = 1;
      private test.ComplexBlob.SubGroup blob_ = test.ComplexBlob.SubGroup.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          test.ComplexBlob.SubGroup, test.ComplexBlob.SubGroup.Builder, test.ComplexBlob.SubGroupOrBuilder> blobBuilder_;
      /**
       * <code>optional .test.SubGroup blob = 1;</code>
       */
      public boolean hasBlob() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .test.SubGroup blob = 1;</code>
       */
      public test.ComplexBlob.SubGroup getBlob() {
        if (blobBuilder_ == null) {
          return blob_;
        } else {
          return blobBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .test.SubGroup blob = 1;</code>
       */
      public Builder setBlob(test.ComplexBlob.SubGroup value) {
        if (blobBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          blob_ = value;
          onChanged();
        } else {
          blobBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .test.SubGroup blob = 1;</code>
       */
      public Builder setBlob(
          test.ComplexBlob.SubGroup.Builder builderForValue) {
        if (blobBuilder_ == null) {
          blob_ = builderForValue.build();
          onChanged();
        } else {
          blobBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .test.SubGroup blob = 1;</code>
       */
      public Builder mergeBlob(test.ComplexBlob.SubGroup value) {
        if (blobBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              blob_ != test.ComplexBlob.SubGroup.getDefaultInstance()) {
            blob_ =
              test.ComplexBlob.SubGroup.newBuilder(blob_).mergeFrom(value).buildPartial();
          } else {
            blob_ = value;
          }
          onChanged();
        } else {
          blobBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .test.SubGroup blob = 1;</code>
       */
      public Builder clearBlob() {
        if (blobBuilder_ == null) {
          blob_ = test.ComplexBlob.SubGroup.getDefaultInstance();
          onChanged();
        } else {
          blobBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .test.SubGroup blob = 1;</code>
       */
      public test.ComplexBlob.SubGroup.Builder getBlobBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBlobFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .test.SubGroup blob = 1;</code>
       */
      public test.ComplexBlob.SubGroupOrBuilder getBlobOrBuilder() {
        if (blobBuilder_ != null) {
          return blobBuilder_.getMessageOrBuilder();
        } else {
          return blob_;
        }
      }
      /**
       * <code>optional .test.SubGroup blob = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          test.ComplexBlob.SubGroup, test.ComplexBlob.SubGroup.Builder, test.ComplexBlob.SubGroupOrBuilder> 
          getBlobFieldBuilder() {
        if (blobBuilder_ == null) {
          blobBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              test.ComplexBlob.SubGroup, test.ComplexBlob.SubGroup.Builder, test.ComplexBlob.SubGroupOrBuilder>(
                  blob_,
                  getParentForChildren(),
                  isClean());
          blob_ = null;
        }
        return blobBuilder_;
      }

      // required int32 testInt = 2;
      private int testInt_ ;
      /**
       * <code>required int32 testInt = 2;</code>
       */
      public boolean hasTestInt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 testInt = 2;</code>
       */
      public int getTestInt() {
        return testInt_;
      }
      /**
       * <code>required int32 testInt = 2;</code>
       */
      public Builder setTestInt(int value) {
        bitField0_ |= 0x00000002;
        testInt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 testInt = 2;</code>
       */
      public Builder clearTestInt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        testInt_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.SelfBlob)
    }

    static {
      defaultInstance = new SelfBlob(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.SelfBlob)
  }

  public interface SubGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated bytes byteGroup = 1;
    /**
     * <code>repeated bytes byteGroup = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getByteGroupList();
    /**
     * <code>repeated bytes byteGroup = 1;</code>
     */
    int getByteGroupCount();
    /**
     * <code>repeated bytes byteGroup = 1;</code>
     */
    com.google.protobuf.ByteString getByteGroup(int index);

    // optional .test.SubSubGroup subSubGroupA = 2;
    /**
     * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
     */
    boolean hasSubSubGroupA();
    /**
     * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
     */
    test.ComplexBlob.SubSubGroup getSubSubGroupA();
    /**
     * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
     */
    test.ComplexBlob.SubSubGroupOrBuilder getSubSubGroupAOrBuilder();

    // optional .test.SubSubGroup subSubGroupB = 3;
    /**
     * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
     */
    boolean hasSubSubGroupB();
    /**
     * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
     */
    test.ComplexBlob.SubSubGroup getSubSubGroupB();
    /**
     * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
     */
    test.ComplexBlob.SubSubGroupOrBuilder getSubSubGroupBOrBuilder();
  }
  /**
   * Protobuf type {@code test.SubGroup}
   */
  public static final class SubGroup extends
      com.google.protobuf.GeneratedMessage
      implements SubGroupOrBuilder {
    // Use SubGroup.newBuilder() to construct.
    private SubGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SubGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SubGroup defaultInstance;
    public static SubGroup getDefaultInstance() {
      return defaultInstance;
    }

    public SubGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SubGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                byteGroup_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              byteGroup_.add(input.readBytes());
              break;
            }
            case 18: {
              test.ComplexBlob.SubSubGroup.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = subSubGroupA_.toBuilder();
              }
              subSubGroupA_ = input.readMessage(test.ComplexBlob.SubSubGroup.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subSubGroupA_);
                subSubGroupA_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 26: {
              test.ComplexBlob.SubSubGroup.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = subSubGroupB_.toBuilder();
              }
              subSubGroupB_ = input.readMessage(test.ComplexBlob.SubSubGroup.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(subSubGroupB_);
                subSubGroupB_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          byteGroup_ = java.util.Collections.unmodifiableList(byteGroup_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.ComplexBlob.internal_static_test_SubGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.ComplexBlob.internal_static_test_SubGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.ComplexBlob.SubGroup.class, test.ComplexBlob.SubGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<SubGroup> PARSER =
        new com.google.protobuf.AbstractParser<SubGroup>() {
      public SubGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SubGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated bytes byteGroup = 1;
    public static final int BYTEGROUP_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> byteGroup_;
    /**
     * <code>repeated bytes byteGroup = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getByteGroupList() {
      return byteGroup_;
    }
    /**
     * <code>repeated bytes byteGroup = 1;</code>
     */
    public int getByteGroupCount() {
      return byteGroup_.size();
    }
    /**
     * <code>repeated bytes byteGroup = 1;</code>
     */
    public com.google.protobuf.ByteString getByteGroup(int index) {
      return byteGroup_.get(index);
    }

    // optional .test.SubSubGroup subSubGroupA = 2;
    public static final int SUBSUBGROUPA_FIELD_NUMBER = 2;
    private test.ComplexBlob.SubSubGroup subSubGroupA_;
    /**
     * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
     */
    public boolean hasSubSubGroupA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
     */
    public test.ComplexBlob.SubSubGroup getSubSubGroupA() {
      return subSubGroupA_;
    }
    /**
     * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
     */
    public test.ComplexBlob.SubSubGroupOrBuilder getSubSubGroupAOrBuilder() {
      return subSubGroupA_;
    }

    // optional .test.SubSubGroup subSubGroupB = 3;
    public static final int SUBSUBGROUPB_FIELD_NUMBER = 3;
    private test.ComplexBlob.SubSubGroup subSubGroupB_;
    /**
     * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
     */
    public boolean hasSubSubGroupB() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
     */
    public test.ComplexBlob.SubSubGroup getSubSubGroupB() {
      return subSubGroupB_;
    }
    /**
     * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
     */
    public test.ComplexBlob.SubSubGroupOrBuilder getSubSubGroupBOrBuilder() {
      return subSubGroupB_;
    }

    private void initFields() {
      byteGroup_ = java.util.Collections.emptyList();
      subSubGroupA_ = test.ComplexBlob.SubSubGroup.getDefaultInstance();
      subSubGroupB_ = test.ComplexBlob.SubSubGroup.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasSubSubGroupA()) {
        if (!getSubSubGroupA().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasSubSubGroupB()) {
        if (!getSubSubGroupB().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < byteGroup_.size(); i++) {
        output.writeBytes(1, byteGroup_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, subSubGroupA_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, subSubGroupB_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < byteGroup_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(byteGroup_.get(i));
        }
        size += dataSize;
        size += 1 * getByteGroupList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, subSubGroupA_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, subSubGroupB_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static test.ComplexBlob.SubGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.ComplexBlob.SubGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.ComplexBlob.SubGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.ComplexBlob.SubGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.ComplexBlob.SubGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.ComplexBlob.SubGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static test.ComplexBlob.SubGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static test.ComplexBlob.SubGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static test.ComplexBlob.SubGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.ComplexBlob.SubGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(test.ComplexBlob.SubGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.SubGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements test.ComplexBlob.SubGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.ComplexBlob.internal_static_test_SubGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.ComplexBlob.internal_static_test_SubGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.ComplexBlob.SubGroup.class, test.ComplexBlob.SubGroup.Builder.class);
      }

      // Construct using test.ComplexBlob.SubGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSubSubGroupAFieldBuilder();
          getSubSubGroupBFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        byteGroup_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        if (subSubGroupABuilder_ == null) {
          subSubGroupA_ = test.ComplexBlob.SubSubGroup.getDefaultInstance();
        } else {
          subSubGroupABuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (subSubGroupBBuilder_ == null) {
          subSubGroupB_ = test.ComplexBlob.SubSubGroup.getDefaultInstance();
        } else {
          subSubGroupBBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.ComplexBlob.internal_static_test_SubGroup_descriptor;
      }

      public test.ComplexBlob.SubGroup getDefaultInstanceForType() {
        return test.ComplexBlob.SubGroup.getDefaultInstance();
      }

      public test.ComplexBlob.SubGroup build() {
        test.ComplexBlob.SubGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public test.ComplexBlob.SubGroup buildPartial() {
        test.ComplexBlob.SubGroup result = new test.ComplexBlob.SubGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          byteGroup_ = java.util.Collections.unmodifiableList(byteGroup_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.byteGroup_ = byteGroup_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (subSubGroupABuilder_ == null) {
          result.subSubGroupA_ = subSubGroupA_;
        } else {
          result.subSubGroupA_ = subSubGroupABuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (subSubGroupBBuilder_ == null) {
          result.subSubGroupB_ = subSubGroupB_;
        } else {
          result.subSubGroupB_ = subSubGroupBBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.ComplexBlob.SubGroup) {
          return mergeFrom((test.ComplexBlob.SubGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.ComplexBlob.SubGroup other) {
        if (other == test.ComplexBlob.SubGroup.getDefaultInstance()) return this;
        if (!other.byteGroup_.isEmpty()) {
          if (byteGroup_.isEmpty()) {
            byteGroup_ = other.byteGroup_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureByteGroupIsMutable();
            byteGroup_.addAll(other.byteGroup_);
          }
          onChanged();
        }
        if (other.hasSubSubGroupA()) {
          mergeSubSubGroupA(other.getSubSubGroupA());
        }
        if (other.hasSubSubGroupB()) {
          mergeSubSubGroupB(other.getSubSubGroupB());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasSubSubGroupA()) {
          if (!getSubSubGroupA().isInitialized()) {
            
            return false;
          }
        }
        if (hasSubSubGroupB()) {
          if (!getSubSubGroupB().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.ComplexBlob.SubGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.ComplexBlob.SubGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated bytes byteGroup = 1;
      private java.util.List<com.google.protobuf.ByteString> byteGroup_ = java.util.Collections.emptyList();
      private void ensureByteGroupIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          byteGroup_ = new java.util.ArrayList<com.google.protobuf.ByteString>(byteGroup_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes byteGroup = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getByteGroupList() {
        return java.util.Collections.unmodifiableList(byteGroup_);
      }
      /**
       * <code>repeated bytes byteGroup = 1;</code>
       */
      public int getByteGroupCount() {
        return byteGroup_.size();
      }
      /**
       * <code>repeated bytes byteGroup = 1;</code>
       */
      public com.google.protobuf.ByteString getByteGroup(int index) {
        return byteGroup_.get(index);
      }
      /**
       * <code>repeated bytes byteGroup = 1;</code>
       */
      public Builder setByteGroup(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureByteGroupIsMutable();
        byteGroup_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes byteGroup = 1;</code>
       */
      public Builder addByteGroup(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureByteGroupIsMutable();
        byteGroup_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes byteGroup = 1;</code>
       */
      public Builder addAllByteGroup(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureByteGroupIsMutable();
        super.addAll(values, byteGroup_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes byteGroup = 1;</code>
       */
      public Builder clearByteGroup() {
        byteGroup_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // optional .test.SubSubGroup subSubGroupA = 2;
      private test.ComplexBlob.SubSubGroup subSubGroupA_ = test.ComplexBlob.SubSubGroup.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          test.ComplexBlob.SubSubGroup, test.ComplexBlob.SubSubGroup.Builder, test.ComplexBlob.SubSubGroupOrBuilder> subSubGroupABuilder_;
      /**
       * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
       */
      public boolean hasSubSubGroupA() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
       */
      public test.ComplexBlob.SubSubGroup getSubSubGroupA() {
        if (subSubGroupABuilder_ == null) {
          return subSubGroupA_;
        } else {
          return subSubGroupABuilder_.getMessage();
        }
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
       */
      public Builder setSubSubGroupA(test.ComplexBlob.SubSubGroup value) {
        if (subSubGroupABuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subSubGroupA_ = value;
          onChanged();
        } else {
          subSubGroupABuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
       */
      public Builder setSubSubGroupA(
          test.ComplexBlob.SubSubGroup.Builder builderForValue) {
        if (subSubGroupABuilder_ == null) {
          subSubGroupA_ = builderForValue.build();
          onChanged();
        } else {
          subSubGroupABuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
       */
      public Builder mergeSubSubGroupA(test.ComplexBlob.SubSubGroup value) {
        if (subSubGroupABuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              subSubGroupA_ != test.ComplexBlob.SubSubGroup.getDefaultInstance()) {
            subSubGroupA_ =
              test.ComplexBlob.SubSubGroup.newBuilder(subSubGroupA_).mergeFrom(value).buildPartial();
          } else {
            subSubGroupA_ = value;
          }
          onChanged();
        } else {
          subSubGroupABuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
       */
      public Builder clearSubSubGroupA() {
        if (subSubGroupABuilder_ == null) {
          subSubGroupA_ = test.ComplexBlob.SubSubGroup.getDefaultInstance();
          onChanged();
        } else {
          subSubGroupABuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
       */
      public test.ComplexBlob.SubSubGroup.Builder getSubSubGroupABuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSubSubGroupAFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
       */
      public test.ComplexBlob.SubSubGroupOrBuilder getSubSubGroupAOrBuilder() {
        if (subSubGroupABuilder_ != null) {
          return subSubGroupABuilder_.getMessageOrBuilder();
        } else {
          return subSubGroupA_;
        }
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupA = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          test.ComplexBlob.SubSubGroup, test.ComplexBlob.SubSubGroup.Builder, test.ComplexBlob.SubSubGroupOrBuilder> 
          getSubSubGroupAFieldBuilder() {
        if (subSubGroupABuilder_ == null) {
          subSubGroupABuilder_ = new com.google.protobuf.SingleFieldBuilder<
              test.ComplexBlob.SubSubGroup, test.ComplexBlob.SubSubGroup.Builder, test.ComplexBlob.SubSubGroupOrBuilder>(
                  subSubGroupA_,
                  getParentForChildren(),
                  isClean());
          subSubGroupA_ = null;
        }
        return subSubGroupABuilder_;
      }

      // optional .test.SubSubGroup subSubGroupB = 3;
      private test.ComplexBlob.SubSubGroup subSubGroupB_ = test.ComplexBlob.SubSubGroup.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          test.ComplexBlob.SubSubGroup, test.ComplexBlob.SubSubGroup.Builder, test.ComplexBlob.SubSubGroupOrBuilder> subSubGroupBBuilder_;
      /**
       * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
       */
      public boolean hasSubSubGroupB() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
       */
      public test.ComplexBlob.SubSubGroup getSubSubGroupB() {
        if (subSubGroupBBuilder_ == null) {
          return subSubGroupB_;
        } else {
          return subSubGroupBBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
       */
      public Builder setSubSubGroupB(test.ComplexBlob.SubSubGroup value) {
        if (subSubGroupBBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          subSubGroupB_ = value;
          onChanged();
        } else {
          subSubGroupBBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
       */
      public Builder setSubSubGroupB(
          test.ComplexBlob.SubSubGroup.Builder builderForValue) {
        if (subSubGroupBBuilder_ == null) {
          subSubGroupB_ = builderForValue.build();
          onChanged();
        } else {
          subSubGroupBBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
       */
      public Builder mergeSubSubGroupB(test.ComplexBlob.SubSubGroup value) {
        if (subSubGroupBBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              subSubGroupB_ != test.ComplexBlob.SubSubGroup.getDefaultInstance()) {
            subSubGroupB_ =
              test.ComplexBlob.SubSubGroup.newBuilder(subSubGroupB_).mergeFrom(value).buildPartial();
          } else {
            subSubGroupB_ = value;
          }
          onChanged();
        } else {
          subSubGroupBBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
       */
      public Builder clearSubSubGroupB() {
        if (subSubGroupBBuilder_ == null) {
          subSubGroupB_ = test.ComplexBlob.SubSubGroup.getDefaultInstance();
          onChanged();
        } else {
          subSubGroupBBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
       */
      public test.ComplexBlob.SubSubGroup.Builder getSubSubGroupBBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSubSubGroupBFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
       */
      public test.ComplexBlob.SubSubGroupOrBuilder getSubSubGroupBOrBuilder() {
        if (subSubGroupBBuilder_ != null) {
          return subSubGroupBBuilder_.getMessageOrBuilder();
        } else {
          return subSubGroupB_;
        }
      }
      /**
       * <code>optional .test.SubSubGroup subSubGroupB = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          test.ComplexBlob.SubSubGroup, test.ComplexBlob.SubSubGroup.Builder, test.ComplexBlob.SubSubGroupOrBuilder> 
          getSubSubGroupBFieldBuilder() {
        if (subSubGroupBBuilder_ == null) {
          subSubGroupBBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              test.ComplexBlob.SubSubGroup, test.ComplexBlob.SubSubGroup.Builder, test.ComplexBlob.SubSubGroupOrBuilder>(
                  subSubGroupB_,
                  getParentForChildren(),
                  isClean());
          subSubGroupB_ = null;
        }
        return subSubGroupBBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:test.SubGroup)
    }

    static {
      defaultInstance = new SubGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.SubGroup)
  }

  public interface SubSubGroupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 testIntA = 1;
    /**
     * <code>required int32 testIntA = 1;</code>
     */
    boolean hasTestIntA();
    /**
     * <code>required int32 testIntA = 1;</code>
     */
    int getTestIntA();

    // optional int32 testIntB = 2;
    /**
     * <code>optional int32 testIntB = 2;</code>
     */
    boolean hasTestIntB();
    /**
     * <code>optional int32 testIntB = 2;</code>
     */
    int getTestIntB();
  }
  /**
   * Protobuf type {@code test.SubSubGroup}
   */
  public static final class SubSubGroup extends
      com.google.protobuf.GeneratedMessage
      implements SubSubGroupOrBuilder {
    // Use SubSubGroup.newBuilder() to construct.
    private SubSubGroup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SubSubGroup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SubSubGroup defaultInstance;
    public static SubSubGroup getDefaultInstance() {
      return defaultInstance;
    }

    public SubSubGroup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SubSubGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              testIntA_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              testIntB_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return test.ComplexBlob.internal_static_test_SubSubGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return test.ComplexBlob.internal_static_test_SubSubGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              test.ComplexBlob.SubSubGroup.class, test.ComplexBlob.SubSubGroup.Builder.class);
    }

    public static com.google.protobuf.Parser<SubSubGroup> PARSER =
        new com.google.protobuf.AbstractParser<SubSubGroup>() {
      public SubSubGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubSubGroup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SubSubGroup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 testIntA = 1;
    public static final int TESTINTA_FIELD_NUMBER = 1;
    private int testIntA_;
    /**
     * <code>required int32 testIntA = 1;</code>
     */
    public boolean hasTestIntA() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 testIntA = 1;</code>
     */
    public int getTestIntA() {
      return testIntA_;
    }

    // optional int32 testIntB = 2;
    public static final int TESTINTB_FIELD_NUMBER = 2;
    private int testIntB_;
    /**
     * <code>optional int32 testIntB = 2;</code>
     */
    public boolean hasTestIntB() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 testIntB = 2;</code>
     */
    public int getTestIntB() {
      return testIntB_;
    }

    private void initFields() {
      testIntA_ = 0;
      testIntB_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTestIntA()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, testIntA_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, testIntB_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, testIntA_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, testIntB_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static test.ComplexBlob.SubSubGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.ComplexBlob.SubSubGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.ComplexBlob.SubSubGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static test.ComplexBlob.SubSubGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static test.ComplexBlob.SubSubGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.ComplexBlob.SubSubGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static test.ComplexBlob.SubSubGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static test.ComplexBlob.SubSubGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static test.ComplexBlob.SubSubGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static test.ComplexBlob.SubSubGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(test.ComplexBlob.SubSubGroup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code test.SubSubGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements test.ComplexBlob.SubSubGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return test.ComplexBlob.internal_static_test_SubSubGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return test.ComplexBlob.internal_static_test_SubSubGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                test.ComplexBlob.SubSubGroup.class, test.ComplexBlob.SubSubGroup.Builder.class);
      }

      // Construct using test.ComplexBlob.SubSubGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        testIntA_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        testIntB_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return test.ComplexBlob.internal_static_test_SubSubGroup_descriptor;
      }

      public test.ComplexBlob.SubSubGroup getDefaultInstanceForType() {
        return test.ComplexBlob.SubSubGroup.getDefaultInstance();
      }

      public test.ComplexBlob.SubSubGroup build() {
        test.ComplexBlob.SubSubGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public test.ComplexBlob.SubSubGroup buildPartial() {
        test.ComplexBlob.SubSubGroup result = new test.ComplexBlob.SubSubGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.testIntA_ = testIntA_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.testIntB_ = testIntB_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof test.ComplexBlob.SubSubGroup) {
          return mergeFrom((test.ComplexBlob.SubSubGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(test.ComplexBlob.SubSubGroup other) {
        if (other == test.ComplexBlob.SubSubGroup.getDefaultInstance()) return this;
        if (other.hasTestIntA()) {
          setTestIntA(other.getTestIntA());
        }
        if (other.hasTestIntB()) {
          setTestIntB(other.getTestIntB());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTestIntA()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        test.ComplexBlob.SubSubGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (test.ComplexBlob.SubSubGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 testIntA = 1;
      private int testIntA_ ;
      /**
       * <code>required int32 testIntA = 1;</code>
       */
      public boolean hasTestIntA() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 testIntA = 1;</code>
       */
      public int getTestIntA() {
        return testIntA_;
      }
      /**
       * <code>required int32 testIntA = 1;</code>
       */
      public Builder setTestIntA(int value) {
        bitField0_ |= 0x00000001;
        testIntA_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 testIntA = 1;</code>
       */
      public Builder clearTestIntA() {
        bitField0_ = (bitField0_ & ~0x00000001);
        testIntA_ = 0;
        onChanged();
        return this;
      }

      // optional int32 testIntB = 2;
      private int testIntB_ ;
      /**
       * <code>optional int32 testIntB = 2;</code>
       */
      public boolean hasTestIntB() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 testIntB = 2;</code>
       */
      public int getTestIntB() {
        return testIntB_;
      }
      /**
       * <code>optional int32 testIntB = 2;</code>
       */
      public Builder setTestIntB(int value) {
        bitField0_ |= 0x00000002;
        testIntB_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 testIntB = 2;</code>
       */
      public Builder clearTestIntB() {
        bitField0_ = (bitField0_ & ~0x00000002);
        testIntB_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:test.SubSubGroup)
    }

    static {
      defaultInstance = new SubSubGroup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:test.SubSubGroup)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_SelfBlob_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_SelfBlob_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_SubGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_SubGroup_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_test_SubSubGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_test_SubSubGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ComplexBlob.proto\022\004test\"9\n\010SelfBlob\022\034\n" +
      "\004blob\030\001 \001(\0132\016.test.SubGroup\022\017\n\007testInt\030\002" +
      " \002(\005\"o\n\010SubGroup\022\021\n\tbyteGroup\030\001 \003(\014\022\'\n\014s" +
      "ubSubGroupA\030\002 \001(\0132\021.test.SubSubGroup\022\'\n\014" +
      "subSubGroupB\030\003 \001(\0132\021.test.SubSubGroup\"1\n" +
      "\013SubSubGroup\022\020\n\010testIntA\030\001 \002(\005\022\020\n\010testIn" +
      "tB\030\002 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_test_SelfBlob_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_test_SelfBlob_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_SelfBlob_descriptor,
              new java.lang.String[] { "Blob", "TestInt", });
          internal_static_test_SubGroup_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_test_SubGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_SubGroup_descriptor,
              new java.lang.String[] { "ByteGroup", "SubSubGroupA", "SubSubGroupB", });
          internal_static_test_SubSubGroup_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_test_SubSubGroup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_test_SubSubGroup_descriptor,
              new java.lang.String[] { "TestIntA", "TestIntB", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
